# Project labels
- name: "project: data publicity"
  color: "#E000AC"
  description: Related to sharing the data used for our applications publicly

- name: "project: ETL"
  color: "#E000AC"
  description: Related to setting up/maintaining ETL for projects

- name: "project: maintenance"
  color: "#E000AC"
  description: Related to regular maintenance for our projects

- name: "project: mastodon"
  color: "#E000AC"
  description: Related to moving projects from Twitter to Mastodon

- name: "project: new departments"
  color: "#E000AC"
  description: Related to adding data for new departments

- name: "project: new services"
  color: "#E000AC"
  description: Related to spinning up new services

- name: "project: OO enhancements"
  color: "#E000AC"
  description: Related to new enhancements to OpenOversight

# Dependency labels
- name: "pip"
  color: "#C2E0C6"
  description: Python dependency changes

- name: "npm"
  color: "#4F4888"
  description: Node.js dependency changes

- name: "docker/env"
  color: "#006B75"
  description: Docker, environment, or CI changes

- name: "github-actions"
  color: "#1D76DB"
  description: GitHub Action dependency changes

- name: "dependency"
  color: "#BFD4F2"
  description: Dependency upgrades
